services:
  - type: web
    name: dcard-linebot
    env: docker
    plan: free
    branch: main
    autoDeploy: true
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        value: your_real_token
      - key: LINE_CHANNEL_SECRET
        value: your_real_secret